apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloack
spec:
  releaseName: keycloak 
  interval: 5m
  install:
    remediation:
      retries: -1
    crds: Create
  chart:
    spec:
      chart: keycloak
      version: '19.3.4'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values 
      valuesKey: keycloak-values.yaml
      optional: false
