apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus
  interval: 5m
  install:
    remediation:
      retries: -1
    crds: Create
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '0.72.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-values
      valuesKey: kube-prometheus-stack-values.yaml
      optional: false
