apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-prometheus-stack.yaml
- namespace.yaml
- secrets.enc.yaml
- dashboards

configMapGenerator:
  - name: kube-prometheus-values
    files:
      - kube-prometheus-stack-values.yaml
    options:
      disableNameSuffixHash: true

