---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    kube-prometheus-stack-values.yaml:
      grafana: 
        adminPassword: AgBVbafSqjPzygrWeCEu/Mn4+MGi0MLbzBYXt65fg3tAj/gvM1mB3CoxIG0a4BaPPruV4lgLAyKZX97P2I7mCXeWr2fxP80J7E2OaU1Q0S6z8eQSVEadc/Zy8zyiCS9NRqU2I8ICJNya3g1Nx3M65Gq5BWTurYEgCSk93iQcBP6H6P9F9aVAMPgCsNuzufFCjcFOwNl6qmO2ucSDuwQ9YjC/FFzaGPzXtf8JeDTlSQX5b9l0WrNNShib+IuYIal0emEQSqNRbxDCMewUYBbhFSFfUb0qf3gLalzad6Md15T5A6+rNj+vicI1MBqrYDJ1fKJvlIqL1RrRg77+fBpA0zjw0a20LETo3QRf2LavmszM3BwR4rgeDOY58Xu+7Go5dY7TFFc2pgmjTBxaxzrJhF18dtooye7XBwRYru8M3S2w6JZZdYQszTEhmKNHVX40J65Vi3Mrvv7yJRp05Jrob9pAjbcuXO+vx3gZJw7QTGZ/bVe3Auvq0zIXyik98QEKKSM7cfb/P48aqs2JravR7H5IW1mjKGP9gjWYGhd+4EJYLAKMMICpfE2ehe0N5rwXBeTDahp0l1FmVDaoZLTqKWesipuQT8Pu8bWbU0TBM+OI8W+eyCnN8KmKk0xUXOBvvme5iy1wMR4VEM4cLettQBJg5wk/EFmt75imSrMLXIYetLEFTszFxlXWsfJHsWMr6pR9ZQvECVN8Q6rf
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
