---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    values: AgDMwE78qkTMkHiQeHLjqNdPhKvXAS5ykRxQ9oSZ0KiQZJkCgl9wJYXaCNi4j/+08Br95Gq5PHNZW2Sn8EeFa5TyoYwOSsQieP4DHvzlopP+g4OlCWvnB+xYRldAIoQT17Am5zL9RzGnX4Xg3jQmqEOOsOrInuAxjTYRabgZB6z4kSNoKI8GnZ3jYsIW9tbwEcRAZPImm9zRPo4DyR65RhC+x4AZnEXCybhTW6MHExL+8ADv8wQjo9z8BJHidr3IQPgW+RBsqH4qN/2lBX/4O8yIIlW9N4n83CRXFN+d0ffvc8XsaFzwfvUcm+kO5anDwJTh8QahND5jcVJwOkzfLBjTVFAVkCz9rOzhDCLUN6SjaHdkftgBc2BL8T9BpZWTvot0NrfJk2PsRpg3KssyUe9o9FhS3pEH+89KS/nVOeMu9G7s8mEMEJ1lrRJ2hgbFTL0VEXx+XRRqptfrz65qOk1ITg9Rss5Tpi5hbl8luV2kgjF470uL4LZtWW2DSP6lbFbCHhvjwxjZMXKRIJUIaSS/ta4/TU59XshP9/kv9jN6GO6qLAQ45uFd3RvjDearowh2JGxzWey04wcm5t3xGf0IRnI9MT7c7l62IFrLaEDFqEIsyvaSTFZMBj2z3qeJQSiBrZxauXdlV1sqmNC69NUDF/3cIdpx/aWWHC8/fJiQYEm1H1P2iymO2kbxtn4I5RD6OHoIS3TnFRIPZ0d1VzVe4OVQAECioZs2ofu6CFws4Xo=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
