---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgDgRVYO+XZbPZsp/e1zXJDuztnmiLony8cByC5z02tnbt8TdH94U0iyzkAxhrOYXHKzN9zXXNI6cXCKvx90S8DQEzaoTqza0go5ki3mc52UfmkC/UrDsodDv8dpqYA87AXF03irD3iAYKUUSyMGvTbJ8HauYRt620P0VADVLzuVGImiDp0gB2toKGIDL2ccsxCIc/Ocf1gNE2vLxfhhAgc/TrjOKFwj+f66ADYP4yLl6si50P126sPRkStYf/svggzXW1XGie4dCXVpVX75Xv7Q5IvroSm9m86nPOivcrps8p1H9qzab0Z9zM0KDt73o+l1gKy2eKQNeu2ScbS//lpRn55A7hMVlO8jHCRMCQkYjNWFem20G6vfXKImNNYSovRlRhpTD0xJp0KK4CgejHeDDxrW6UXjmfjFB2iu1cUeWmFsobwL2ihOR5FC+W2J5LUySFwmovnlrDljjy6LyrlekPI8Vo+ZYTnslIpmK6OZ452ijgIGv97oFYcZEX5aZLyg9+ICkfdUO7j/UwgYuC3sanjBlp3Ied6g+XTtllHmgC7S3CJwO+VAUSA5uauzV7riOwJ7vP1dhtJU01LbuH8+QSHUFSKNTscLrdfdVfC0ciarxRIhXcN47YBIGdLjl5nKQcXMln0SRk5pEsJDVhCe7wEfDfu3klcRV9eLgSJhs8cqsHQGmFVFg/RiFT3fjDWhOKY=
    username: AgBR7Nqti/jE8wy0Ns/caoW2zIqp8LRMov7n4XVpquJntywwcWM/0MwbWhxqGZvxC/8ygtt60VbTQZUDm7iuPpSBJBxrz0On4k1qHKcIp4+s736/Jx8ubP83pNSPJEQYOkkJi6zDYDPusn4D+v92KfHBGcI4MEOv8umiV9srXCF6WnodWpH5o0crv5jz/cjngYkqlYMDHBadKNJHqh4W1zEe88s7LRheJNCcAeBVdDTcMbD2C2N7nJLR+VkwKRVD8NuSCfLHR77oPYUMqLk0lKatKqPr0WJW7CwqZ5GzpcltG4n3nbkzhOFoWXuVJqlJtk4Zv+HG6+q3yRcNlRuEZ8iPUywXIpnehY7CuFoWU5JtLQwBsUL++fQk571VZDij9itXty0nqo3Qrmr0QXT7oEcbJTyZP2ZRlMqxTdVPgyuPl0ClbvfvdBfymRf5nHzAynTKMmknNMgVEa3PAdydw1cR6vGs2VP9LQdF0I2nMj9IVsE7Wk9at4cXKA18NyslpqISw0qfTltyrjnxVIPWCBu1rlAGS+cJlpKxIQpPB0J20pCc1feNxms3EWxvdYoTwat0B+SfaIWj718T0FkGiIS0SN+WelQBJzIfY70NVFb4FubFXNaPDQyABAYNN+GfTRv7H93FXR3yA+A/mIHKBkDKYktUdbYugW5xlbN6W7JwecSqQtg53FhqrJ1SsJJ5sPBYLJM=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
