---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgC4K5cAumRyZKX6dGpwfpuJ84SJH9Hb2mGlgX+5ugpLXg+wAsfgMvFoVHH6sxtiUVnzKnaadFhJKKEbt4isC2FRNetYhMWb6lPpxQXf/f4Gtwi86nVbUoO/RFjlGvb8hzCb0Q1CyAGzVCXxfzbd09pvT4BDVrXLtuxIW128TXiJaSgxahT82OzaANCPhbsIEuiiMOhtPH8LKJ4L0x0JHJ/mO4runM1kxGCqnGB9sYFN/q2K548Cnma6E2hU3udpTs1Tusgee7Ho1UGILQgoa+jzw7mfC6CcbEvtvvJvMsjBN6jPeD8hpR84RmmaJN9eJ+udz2MrtCZLGnRYz/wJrQwkx4SdXoOWYeBI8QLJStW330jO0/BIZCADnyh432sGOrErmrQ5trEFuhV9w8+f2/Y4Enfge7pf5fn75DkyxlXpvRcXESEYHI8CI9M7sNV4HgNIiU3zjUsVEmI+Iti3RAuA5qcmoHRKwUGNR+PS1U6i9rjCRXF7rXQuGr9W9Xa1WegGELzHgDYiprmhE2P+hmxvEGkgxvEi2v8YVF5svXJjQKgHRZJ9awxWnxUIQAdIqiCOWIQbEKCcOUkjk8DYRZbkF3Fl+d8XEVXuR+TDoA/py25m5aNf6raRMiY6Sb4mQD0wBlKfLHRbegkaxApSqGOnemuTYYfWC8CNKjpsbmaepWbrivBlvRe8fWqmJ4uMAgohCtw=
    username: AgCa8VxifOnJf7stiXXoR9UnEsj+K3WJrI3dNpaeFs2+QSKIS0OHEwrX/wx4LB0J7xurDXQ9WfFn4fCdU+oewGS9qhWd3gyz7BmqHL8q2ltqvJ+uOMN/mcKy6PBaPKKozz4hnyp04XkZWuE/SXUmUxxUTpsjdw0ORaxEKsqdA9cHFDHgEVGo0r9yR80SyL7131EYpqkjZF7Fz2g+ilYssyS1NwuEoa/UVFB1HpG1PyVPwvN/sYs6ZG3ITuMKzcuvwLCF8g3FPIQkOodMclglBNsESrB39Ty6ratUDko77wpvI37znNluYo3KqtEIBBv2Iqw38Jvd/L04hqYb6hNdhYHVmutr6+Yz5GZ34Q+TlVgXs4TU4jAxQbjdXuOUrWL05Lq2nR19sH2yuBuKyUK3XJSrN2GP1GNsY7i/xDrP0BiJZajf7r9r8TyI1nY3O/8YGxHtMfp/jUV49T1AxMtFlGmdahLZXUNxjRjPI/nGPqG3FUvUVbmKxCoUPogO6g3AVjs7CR4uyaTPaMsWYComl2WdxNNfN/CZNfx+DStSLwIuFoYPademRH7C1g6zIxc7sAXmflxoyeycjNa0tt/dlsyFAsL1Lh6nMiqQZRV1So1+H5VhidKsuNVQICvVlpsVyQNre5npoOr9kU3VswhuxYERkLDQRGnCIhMPd+wr/bIyJJNxRd9yFBKvdduPHCH2FsJoVFM=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
