---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgCdcV6Syf6I5sv82TYIKbJmEXYOYRX7iprMfc9ZqIEIoeeF2AGpgK0uRBVfqTRuN31zkfbv+0LQeqcYwiH84h/llnIEyK1k1lGluUp4GIt4zjAXM+XAkgK3lSU0dVp/WBcbaMHbcXAOnejNgkAqpKtNgJRNTjq3ZGBhERiunpVdhfOtVtyKGUVVFhlYzAays7OAzdQ4IUMsMeo1713VuMjZOicYd+iSjzQXPtBRq+/3c+zmMLDF3w3Qk9Xu7+m07vacEDtzgzieIZYykt6WxefnzuR7jDeYVkn6qp2HwKh23eHS6OHlhmbO2J+stcC9tLiKq3+YhAECzEOH/Hz/MJgfWxOHZeaJi8B9E0WQCK7UBMYyd6SVckWncIqe1n808c/g43bbDS65IHz8R9aumeJAbitWI8QS7Z0qZmCPuMohD3ztsR5wIMnRpWP+6tknJN53O9iUn/aL13R/1YqqngrteYT2llQWUo0R4th63vvDYtAF87sxdfhcfauDmVU8R5+d4JIn+e4zicutCHW/QAhgm3l2Gzx7/RznPb/mohk/w5VC8P8PepKnKEUUKuA3da0N9DP1upFfiDwQJqKlz4E3CYyRxpv+qhfrk4XEBMpp5KchPGDjETXReDqQNZX4tgJwYU5L0VAURO3CB/3W2Qm6svI+8qDtqry1+zZRJ1y5pF1lp3wuk5DpB4CVrjdaTfLAdks=
    username: AgCHSTSllYhwZJH49oCm2IGpk+zzMKssg1PdirED5rUq6db1EtyEq+44Pr3LZG4M3U9xNSrnDzih+lBGAuuNMmRaCMxPeELCSj3URHtE75sV7Iacg5Fb/cJVuY7fkZktXGX/519YulwJKHFr+UW2xkBkyzY7jhTCBicqScAoG6ELkfvyC4796ZIww93D6elMWYvR4cGmKN+5OsiSv+8dkLNEGclPz4Gc7O4e39Q/+LnlnHcR1NOenenIfX6V/QuOtjcKUilPZo1aRvF1St+FnmURoBNb3LXIPAMrIwQDUN8aolB3yo01vtUcfaWkKNcOj9pE3yq3VEDvvAdIKgEyyhaOZglVp7swnZOuJSv2kHEJwpBr2boEQHbuKlFXWFrxNcAQ4fUlklw37uRDz6GIdUlfpoqd6S7rCprKlrv+u24unwKzzK6LI7AmFExLWYKW4w5LUkQ/kepjK809nffPgQdreevFs6lRKKaNZ9ke4vO18vApkfFnRbtRLV+c1H+pl/QXLMRg6Qcev3lWtlLckfpHuNKnVZmXjhxWSEzvzLyMFKR5PEZ6QB7UYlSuuZ5tnQ2mgNipa/DegYKuIFQUaKx7btOJvtpUdRda1lyKKtDi2iWek1jvfZz9yB3YcJ6cWvrDjElfiejfZPyIHxFXrxluk2evdCk5G3r1KPzXHR087iNu+bSIYIut9aK2SsAAuxN0JgA=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: monitoring
