apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: auth
  sourceRef:
    kind: GitRepository
    name: kubetrain
  path: "./auth"
  prune: true
  timeout: 1m
