apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kubetrain
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kubetrain
  filterTags:
    pattern: '^develop-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
