apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubetrain
  namespace: flux-system
spec:
  interval: 10s
  url: ssh://git@github.com/xthale/kubetrain-devops 
  secretRef:
    name: flux-system
  ref:
    branch: main
