apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubetest
  namespace: flux-system
spec:
  interval: 10s
  url: https://github.com/xThale/kubetrain-devops
  secretRef:
    name: flux-system
  ref:
    branch: main
