apiVersion: v1
kind: Service
metadata:
  name: kubetrain
  labels:
    app: kubetrain
spec:
  selector:
    app: kubetrain
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubetrain-service-monitor
spec:
  selector:
    matchLabels:
      app: kubetrain
  endpoints:
    - port: http-web 
      path: /q/metrics
      interval: 15s
      scheme: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetrain
  labels:
    app: kubetrain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetrain
  template:
    metadata:
      labels:
        app: kubetrain
    spec:
      containers:
      - name: kubetrain
        image: docker.io/xthale/kubetrain:develop-1711364208 # {"$imagepolicy": "flux-system:kubetrain"}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
